config/routes.rb
Rails.application.routes.draw do
  resources :applicants do 
  	collection do 
	  	get 'create_conf'
	  	get 'thank_you'
		end
  end
  root 'applicants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/applicant.rb
class Applicant < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/status.rb
class Status < ApplicationRecord
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_action :set_applicant, only: [:show, :edit, :update, :destroy]

  # GET /applicants
  # GET /applicants.json
  def index
    @applicants = Applicant.all
  end

  # GET /applicants/1
  # GET /applicants/1.json
  def show
    @applicant = Applicant.new(applicant_params)
  end

  # GET /applicants/new
  def new
    @applicant = Applicant.new
  end

  # GET /applicants/1/edit
  def edit
  end

  def thank_you
    # clear session
    session[session[:email]] = {}
    
  end

  def create
    @applicant = Applicant.new(applicant_params)
    # instead of saving it lets imagine that I sent it to some API, and if i get a 200 back i will redirect over
    if @applicant.save
      redirect_to thank_you_applicants_path
    else
      
      redirect_to :back
    end
  end

  # POST /applicants
  # POST /applicants.json
  def create_conf
    session[:email] = applicant_params[:email]
    if session[applicant_params[:email]].nil?
      session[applicant_params[:email]] = {}
    end
    session[applicant_params[:email]][:first_name] = applicant_params[:first_name]
    session[applicant_params[:email]][:last_name] = applicant_params[:last_name]
    session[applicant_params[:email]][:email] = applicant_params[:email]
    session[applicant_params[:email]][:phone] = applicant_params[:phone]
    session[applicant_params[:email]][:zip_code] = applicant_params[:zip_code]
  end


  private
    # Use callbacks to share common setup or constraints between actions.
  def set_applicant
    @applicant = Applicant.find(params[:id])
  end

  def applicant_params
    params.require(:applicant).permit(:id, :first_name, :last_name, :email, :phone, :zip_code, :referrer)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/applicants/_form.html.erb
<%= form_for(applicant) do |f| %>
  <% if applicant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(applicant.errors.count, "error") %> prohibited this applicant from being saved:</h2>

      <ul>
      <% applicant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applicants/create_conf.html.erb
<div class="container main_form">
			<h1>Almost there!</h1>

		<div class="col col-lg-12 form-contain">
		<h3>Please confirm your information:</h3>
    	<div class="conf_contain">
    		
    	<b>
	    	First Name:
    	</b>
    	 <%= session[session[:email]]['first_name'] %>
    	</div>
    	<div class="conf_contain">
    		
    	<b>
	    	Last Name:
    	</b>
    	 <%= session[session[:email]]['last_name'] %>
    	</div>
    	<div class="conf_contain">
    		
    	<b>
	    	Email:
    	</b>
    	 <%= session[session[:email]]['email'] %>
    	</div>
    	<div class="conf_contain">
    		
    	<b>
	    	Phone:
    	</b>
    	 <%= session[session[:email]]['phone'] %>
    	</div>
    	<div class="conf_contain">
    		
    	<b>
	    	Zip Code:
    	</b>
    	 <%= session[session[:email]]['zip_code'] %>
    	</div>
			
		</div>

		<form action="<%= applicants_path %>" class='submit_form' method="POST" style="display: none;">
			<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
			<input type="hidden" value="<%= session[:first_name]%>" name="applicant[first_name]">
			<input type="hidden" value="<%= session[:last_name]%>" name="applicant[last_name]">
			<input type="hidden" value="<%= session[:email]%>" name="applicant[email]">
			<input type="hidden" value="<%= session[:phone]%>" name="applicant[phone]">
			<input type="hidden" value="<%= session[:zip_code]%>" name="applicant[zip_code]">
			
		</form>
		<a href="" class='btn btn-lg conf_buttons confirm'>Confirm</a>
		<a href="<%= new_applicant_path %>" class='btn btn-lg conf_buttons back'>Back</a>
</div>

<script>
	$('body').on('click', '.confirm', function(event) {
		event.preventDefault();
		$('.submit_form').trigger('submit');
	});
</script>

app/views/applicants/edit.html.erb
<h1>Editing Applicant</h1>

<%= render 'form', applicant: @applicant %>

<%= link_to 'Show', @applicant %> |
<%= link_to 'Back', applicants_path %>

app/views/applicants/index.html.erb
  


<div class="container main_form" style="background-color: transparent;">
  <a href="<%= new_applicant_path %>" class='btn btn-lg enter'>Apply Now</a>
</div>


<style>
</style>

app/views/applicants/new.html.erb
<div class="container main_form">
		<div class="col col-lg-12 form-contain">
			<h1>Get paid to shop!</h1>
			<div class="form-group">
				<form action="<%= create_conf_applicants_path %>" id='new_applicant' method="GET">
					<div class="names row">
						<div class="input string form-group required col col-lg-6">
							<input autocorrect="off" tabindex="1" autofocus="autofocus" class="string required form-control" required="required" aria-required="true" placeholder="First Name" type="text" name="applicant[first_name]" value="<%= session[:email].nil? ? '' : session[session[:email]]['first_name'] %>" id="applicant_first_name">
						</div>
						<div class="input string form-group required col col-lg-6">
							<input autocorrect="off" tabindex="2" class="string required form-control" required="required" aria-required="true" placeholder="Last Name" type="text" name="applicant[last_name]" value="<%= session[:email].nil? ? '' : session[session[:email]]['last_name'] %>" id="applicant_last_name">
						</div>
					</div>
					<div class="input email form-group required applicant_email">
						<input tabindex="3" required="required" aria-describedby="applicant_email_error" class="string email required form-control" aria-required="true" placeholder="Email" type="email" name="applicant[email]" value="<%= session[:email].nil? ? '' : session[session[:email]]['email'] %>" id="applicant_email">
					</div>

					<div class="input tel form-group required applicant_phone">
						<input tabindex="4" aria-describedby="applicant_phone_error" class="required form-control" required="required" aria-required="true" placeholder="Cell Phone Number" type="tel" name="applicant[phone]" value="<%= session[:email].nil? ? '' : session[session[:email]]['phone'] %>" id="applicant_phone">
					</div>

					<div class="input string form-group required applicant_zip_code">
						<input tabindex="5" aria-describedby="applicant_zip_code_error" class="required form-control" required="required" aria-required="true" placeholder="Zip code" type="text" name="applicant[zip_code]" value="<%= session[:email].nil? ? '' : session[session[:email]]['zip_code'] %>" id="applicant_zip_code">
					</div>

					</button>
					<p class="legal">
						We'll use this information to communicate with you throughout the process.
					</p>
				</div>
				<input type="submit" class='btn btn-lg submit'>
			</form>
		</div>
</div>

app/views/applicants/show.html.erb
<div class="container main_form">
	<h2>Your information</h2>
	<div class="names row">
		<div class="input string form-group required col col-lg-6">
			<input autocorrect="off" tabindex="1" autofocus="autofocus" class="string required form-control" required="required" aria-required="true" placeholder="First Name" type="text" name="applicant[first_name]" id="applicant_first_name">
		</div>
		<div class="input string form-group required col col-lg-6">
			<input autocorrect="off" tabindex="2" class="string required form-control" required="required" aria-required="true" placeholder="Last Name" type="text" name="applicant[last_name]" id="applicant_last_name">
		</div>
	</div>
	<div class="input email form-group required applicant_email">
		<input tabindex="3" required="required" aria-describedby="applicant_email_error" class="string email required form-control" aria-required="true" placeholder="Email" type="email" name="applicant[email]" id="applicant_email">
	</div>

	<div class="input tel form-group required applicant_phone">
		<input tabindex="4" aria-describedby="applicant_phone_error" class="required form-control" required="required" aria-required="true" placeholder="Cell Phone Number" type="tel" name="applicant[phone]" id="applicant_phone">
	</div>

	<div class="input string form-group required applicant_zip_code">
		<input tabindex="5" aria-describedby="applicant_zip_code_error" class="required form-control" required="required" aria-required="true" placeholder="Zip code" type="text" name="applicant[zip_code]" id="applicant_zip_code">
	</div>

	<div class="input string form-group optional applicant_referer">
		<input tabindex="100" autocomplete="referrer" class="string optional form-control" placeholder="Referral Code (optional)" type="text" name="applicant[referer]" id="applicant_referer">
	</div>
  <a href="#" class='btn btn-lg btn-primary enter go_back'>Cancel</a>
  <a href="#" class='btn btn-lg btn-primary enter confirm'>Confirm</a>
</div>

app/views/applicants/thank_you.html.erb
<div class="container main_form thanks">
	Thank You!
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstacartShopper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>

  <body>
    <div class="container bg">
    <% if flash[:error] %>
      <div class="error_report update-box-sub" style="display: block;background-color: red;color: white;"><%= flash[:error] %></div>
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>


<style>

  .submit {
    float: right;
    width: 100%;
    background-color: green;
    color: white;
    font-size: 34px;
  }

  .enter {
    color: black;
    background-color: green;
    width: 100%;
  }

  .bg {
    position: fixed;
    width: 100%;
    height: 100%;
    background-image: url(<%= asset_path 'picture.jpg' %>);
    background-repeat:no-repeat;
    background-position:left center;
    background-size: cover;
  }

  .form-control {
    background-color: #fff9ed;
    height: 50px;
    font-size: 22px;
    padding: 41px;
  }

  .container {
        background-color: white;
        padding: 10px;
  }

  .main_form {
    border-radius: 6px;
    font-family: 'Open Sans', 'Helvetica Neue', Arial, Helvetica, sans-serif;
    width: 30%;
    position: relative;
    margin-top: 10%;

  }

  .main_form h1 {
    font-size: 53px;
    font-weight: 700;
    float: center;
    width: 100%;
    text-align: center;
    margin: 0 auto;
    padding-bottom: 4%;
    padding-top: 4%;
  }

  .thanks {
    font-size: 30px;
    text-align: center;
    padding: 24px;
  }

  a:visited {
    color: white;
  }

  a:hover {
    color: white;
  }

  .conf_contain {
    padding: 20px;
    background-color: #fffeee;
    margin-bottom: 6px;
    font-size: 20px;
  }

  .conf_buttons {
    color: white;
    background-color: green;
    width: 49%;
  }

  .back {
    background-color: red;
    color: white;
  }


</style>